### ISSUE TITLE
[bounty] searching tokens

### ISSUE THREAD

**Issue by lazarovicedo** [Rovak/wallet-web#102]
As more and more tokens are created Token view is going to need pagination and 
![searchtoken](https://user-images.githubusercontent.com/1026755/38946583-3798d02a-433a-11e8-94ff-8f9f9d45d382.png)
also token name search.

**Comment by AhnSinYong** [comment]
Maybe I can do it.

**Comment by lazarovicedo** [comment]
I have started already to work on this, based on the Accounts search code
that is already done.


Saludos,

Lazaro Vicedo
lazarovicedo@gmail.com

2018-05-02 7:56 GMT+02:00 AhnSinYong <notifications@github.com>:

**Comment by AhnSinYong** [comment]
I created a basic search bar that works with redux and router.
It would be better if you refer to it when you work.

**Comment by lazarovicedo** [comment]
AhnSinYong , in this case it would be better if you could finish this
feature, don't worry about my code, the code I´ve done is not that much.


Saludos,

Lazaro Vicedo
lazarovicedo@gmail.com

2018-05-02 8:58 GMT+02:00 AhnSinYong <notifications@github.com>:

**Comment by AhnSinYong** [comment]
I was not worried about your code, but I told you I wanted to help you work.
I'm sorry to make you think so.
