### ISSUE TITLE
CONFUSION IN PEOPLE FOR TRX IN TESTNET

### ISSUE THREAD

**Issue by btn99** [Rovak/wallet-web#106]
The trx in Testnet Thai is tronscan.com accounts is Real but People are thinking it's of no use.That trx is a secret Giveaway by Justin.

**Comment by btn99** [comment]
You are Loser

**Comment by Rovak** [comment]
@shanadas consider that less informed people believe that crypto is free money and airdrops are being done regularly. This could be a legitimate concern and not "spam".

@btn99 we don't tolerate insults, please be respectful to each other. I'll be closing this issue. If you believe this is a major concern then please provide some references.

**Comment by shanadas** [comment]
@Rovak I understand, thanks for the update.
