### ISSUE TITLE
/tokens/create - Exchange rate not calculated anymore [Bounty] 

### ISSUE THREAD

**Issue by miimiispets** [Rovak/wallet-web#110]
Token exchange rate isn't calculated and displayed live on screen anymore.
This function seems to be broken or has been deactivated.

Sollution is to re-instate calculation.
This was functioning previously.
![bugs tokencreate - not calculating exchange rate](https://user-images.githubusercontent.com/38192052/39083858-13b7e900-456c-11e8-95e4-8a3d4e0e5c7d.PNG)

**Comment by AhnSinYong** [comment]
I am missing while separating the form.
It's corrected.
It will be applied to the next deployment.
Thank you for letting me know.
