### ISSUE TITLE
[Suggestion][Bug] Network Page - Representative Number starting with 0/Responsive Design

### ISSUE THREAD

**Issue by fbsobreira** [Rovak/wallet-web#116]
1. What did you do?
   - On desktop (chrome/firefox/opera) access https://tronscan.org/#/network
   - reduce the window size
   - On mobile (chrome) access https://tronscan.org/#/network

2. What did you expect to see?
   - List of representatives order by votes starting with number 1.
   - Block statistics

3. What did you see instead?
   - List of representatives order by votes starting with number 0.
   - No block statistics
   - "Newest account" (Label string and number) are not showing properly

![tronnetworkrepresentative](https://user-images.githubusercontent.com/8503176/39329320-f3aaeb2c-496b-11e8-822e-c7134395521c.png)

4. Suggestion
   - Add responsive design

**Comment by Jacob8765** [comment]
I'll look into this.

**Comment by Jacob8765** [comment]
This should be solved in #150. Can you confirm?

**Comment by fbsobreira** [comment]
Great! looks good for me...
