### ISSUE TITLE
high cpu usage 

### ISSUE THREAD

**Issue by Johnsavadkuhi** [Rovak/wallet-web#125]
http://localhost:3000/#/network/nodes

the nodes page takes  100% or more cpu  it is because of map animation i think    
![takealot](https://user-images.githubusercontent.com/6722877/39407148-fe225a5a-4bd6-11e8-8046-a528117ad34e.png)

**Comment by Rovak** [comment]
This is a problem with echarts that i don't intend to fix myself, i guess this issue should be moved to the echarts project
