### ISSUE TITLE
[Bounty] missing key for string "Recent Blocks"

### ISSUE THREAD

**Issue by DevObs1** [Rovak/wallet-web#135]
Missing key for string "Recent Blocks" (/ blockchain)

![image](https://user-images.githubusercontent.com/31596745/39546811-ee3ac380-4e55-11e8-9b3e-a7f1e97998bc.png)

![image](https://user-images.githubusercontent.com/31596745/39546830-fc9ebbac-4e55-11e8-816f-23a4ab26530c.png)

**Comment by AhnSinYong** [comment]
Completed message key addition
