### ISSUE TITLE
reCapcha is needed 

### ISSUE THREAD

**Issue by Johnsavadkuhi** [Rovak/wallet-web#144]
reCapcha is needed for register and login page

**Comment by lazarovicedo** [comment]
the code is done, I´m waiting for a rev
![recaptcha](https://user-images.githubusercontent.com/1026755/39638274-05a40ec0-4fc6-11e8-9df7-b341adb83abb.png)
iew

**Comment by DevObs1** [comment]
Thanks @lazarovicedo 
Can you also add it to the "Register" tab?

**Comment by Rovak** [comment]
A reCaptcha isn't required, all accounts/keys are kept in the browser. Also it is computationally infeasible to try and brute force a private key
