### ISSUE TITLE
[Bounty] Text Overflows from External URL Dialog

### ISSUE THREAD

**Issue by Jacob8765** [Rovak/wallet-web#149]
The text in the external URL dialog overflows from the modal on smaller screens. Image:

![problem1](https://user-images.githubusercontent.com/33853949/39643684-8a96fb9c-4fa3-11e8-92d1-0f751ce9cd0e.PNG)

**Comment by lazarovicedo** [comment]
I would get rid off that warning...by now even my grandma knows that those links take you to an external link.
