### ISSUE TITLE
[Bounty] Suggestion to have tooltip for text where text trimming is applied.

### ISSUE THREAD

**Issue by shanadas** [Rovak/wallet-web#155]
In wallet home page (Blockchain view) it is good to have tool-tip applied on texts where character ellipsis behavior is set as text trimming. Eg: The hash of Last block (highlighted in screenshot)

![image](https://user-images.githubusercontent.com/3648025/39672777-671756f6-514e-11e8-91b7-3f0e2d79eddd.png)

**Comment by Jacob8765** [comment]
I added a tool-tip to the URLs in the Representatives page in #150. If that is what you had in mind, I think I could add it here as well. Here is a screenshot:
![tooltip1](https://user-images.githubusercontent.com/33853949/39674978-39c90996-5122-11e8-933e-61fb5f669282.png)

**Comment by shanadas** [comment]
Yes, this same behavior would be good.
