### ISSUE TITLE
Amount sent to issuer is being multiplied by 1000000 in post data

### ISSUE THREAD

**Issue by shanadas** [Rovak/wallet-web#172]
In token participation, the amount entered in the view is being multiplied by 1000000 in form's post data. See below 2 screenshots of a token participation and corresponding form data submission.

![image](https://user-images.githubusercontent.com/3648025/39687002-ec1f51c8-51e9-11e8-932d-f585dd877a5a.png)

![image](https://user-images.githubusercontent.com/3648025/39687067-3719f368-51ea-11e8-8d29-0a44575e45e1.png)

**Comment by Rovak** [comment]
This is intended, the API requires that TRX is send in `drops`. 1000000 drops = 1 TRX
