### ISSUE TITLE
[Bounty] Minor wording correction

### ISSUE THREAD

**Issue by shanadas** [Rovak/wallet-web#175]
Accounts page heading. Correct the wording to "Most TRX"

![image](https://user-images.githubusercontent.com/3648025/39689344-0dae66b2-51f4-11e8-9dcd-fe5c5daa8ecf.png)

**Comment by bondibox** [comment]
Also, when you register an account it gives you an "address" and a "password" but when you go to your account and click on "show private key" it's the same as the "password" you were given at registration. It looks like the private key IS the password, but some consistency is needed.

**Comment by Jacob8765** [comment]
@shanadas I'll fix these today
