### ISSUE TITLE
[Bounty] Send TRX page - Redirecting to blank page and application unusable state on special character in To field

### ISSUE THREAD

**Issue by shanadas** [Rovak/wallet-web#178]
Go to Send TRX Page --> **Enter a valid To address** --> Now change any one character in address to a special character, say # --> Application redirects to blank page and become useless.

Note - Directly entering special character in To field could not reproduce this issue. One has to enter valid address and then change any one character to special character for reproducing this issue.
![image](https://user-images.githubusercontent.com/3648025/39705074-f5aeff5e-522a-11e8-8b67-1fbe0159aea8.png)

**Comment by AhnSinYong** [comment]
This will be fixed.
