### ISSUE TITLE
[bounty] error when loading home page

### ISSUE THREAD

**Issue by lazarovicedo** [Rovak/wallet-web#185]
Blocks nor transactions are loaded on home page, this is the error:

"Assertion failed"
messagePattern
:
"Assertion failed"
reportErrorToServer
:
true
stack
:
"AssertionError: Assertion failed↵    at new goog.asserts.AssertionError (https://tronscan.org/static/js/main.c22ea9c5.js:26845:603)↵    at Object.goog.asserts.doAssertFailure_ (https://tronscan.org/static/js/main.c22ea9c5.js:26846:126)↵    at Object.goog.asserts.assert (https://tronscan.org/static/js/main.c22ea9c5.js:26846:385)↵    at jspb.BinaryReader.readEnum (https://tronscan.org/static/js/main.c22ea9c5.js:27101:398)↵    at proto.protocol.Transaction.raw.deserializeBinaryFromReader (https://tronscan.org/static/js/main.c22ea9c5.js:30177:86)↵    at jspb.BinaryReader.readMessage (https://tronscan.org/static/js/main.c22ea9c5.js:27092:329)↵    at proto.protocol.Transaction.deserializeBinaryFromReader (https://tronscan.org/static/js/main.c22ea9c5.js:29623:14)↵    at jspb.BinaryReader.readMessage (https://tronscan.org/static/js/main.c22ea9c5.js:27092:329)↵    at Function.proto.protocol.Block.deserializeBinaryFromReader (https://tronscan.org/static/js/main.c22ea9c5.js:31274:14)↵    at Function.proto.protocol.Block.deserializeBinary (https://tronscan.org/static/js/main.c22ea9c5.js:31254:31)"
__proto__
:
goog.debug.Error

**Comment by Rovak** [comment]
Fixed
