### ISSUE TITLE
[Bounty]用户列表展示问题

### ISSUE THREAD

**Issue by micah13433** [Rovak/wallet-web#186]
1.新建的用户在 Accounts 列表无法显示
2.Accounts列表总数不准确，刷新页面线上个数不一致。
![1](https://user-images.githubusercontent.com/3438505/39749091-6432bb78-52e4-11e8-9138-d54d327fe9ea.png)
![2](https://user-images.githubusercontent.com/3438505/39749117-7a87fb2c-52e4-11e8-8aac-3910fd35186a.png)

**Comment by zhaohong** [comment]
have fixed,  the reason is that the wallet-cli connect two server, one is fullnode and the other is soliditynode

**Comment by zhaohong** [comment]
same as https://github.com/tronprotocol/wallet-web/issues/189
