### ISSUE TITLE
Blockchain Explorer Jumps Around

### ISSUE THREAD

**Issue by bondibox** [Rovak/wallet-web#190]
If you navigate to https://tronscan.org/#/ and load the blockchain it does not always display the most recently created block.

For instance, right now I can see block 21491 but if I refresh the page it displays 21482. I have noticed this behavior for 10 days and I believe it's actually connected to the issue I reported at the outset

https://github.com/tronprotocol/java-tron/issues/580

Where the java-tron stalls and then starts multiple threads, it then becomes random which thread the blockchain explorer will report.

I'm also getting random results when I add test TRX and then check my balance. Freezing also has random results, at times offering to freeze my full balance and at other times only recognizing part of my balance available for freezing.

**Comment by zhaohong** [comment]
have fixed, some as https://github.com/tronprotocol/wallet-web/issues/189
