### ISSUE TITLE
[Bounty] Freeze TRX Dialog - Faulty operating element 

### ISSUE THREAD

**Issue by PMD3VSolution** [Rovak/wallet-web#200]
if you click on the Minus button in the Freeze TRX dialog and the current value is 0 the display jumps to 1

befor:
![image](https://user-images.githubusercontent.com/39301026/40055288-ae26a0ce-5847-11e8-9408-e1c855690bf2.png)

after:
![image](https://user-images.githubusercontent.com/39301026/40055329-cf49e3a6-5847-11e8-8ebe-cdea9fc6d608.png)

In my opinion, the value should not change! 0 is 0

**Comment by AhnSinYong** [comment]
Fixed this issue with issue #201
