### ISSUE TITLE
[Bounty] Freeze TRX Dialog - Input of special characters possible

### ISSUE THREAD

**Issue by PMD3VSolution** [Rovak/wallet-web#201]
the following characters can be entered in the input dialog
- (minus)
+ (plus)
![image](https://user-images.githubusercontent.com/39301026/40055883-c958cf14-5849-11e8-990b-6621074d8d02.png)

**Comment by tronmarcus** [comment]
Hi, @PMD3VSolution ,
I am pleased to inform you that you are rewarded TRX from Tron Foundation for your contribution in our Bug Bounty Program in May 2018. Please provide a valid account address that can receive the TRX reward.
Please send the address to my email yanghe@tron.network so we can deliver the TRX on time.
Thanks,
Marcus Yang

**Comment by marcusyanghe** [comment]
Hi, @PMD3VSolution ,
I am pleased to inform you that you are rewarded TRX from Tron Foundation for your contribution in our Bug Bounty Program in May 2018. Please provide a valid account address that can receive the TRX reward.
Please send the address to my email yanghe@tron.network so we can deliver the TRX on time.
Thanks,
Marcus Yang

**Comment by AhnSinYong** [comment]
@marcusyanghe Are you saying that to me?
