### ISSUE TITLE
Account / Voting page / suggestion for improvement 3 [Bounty]

### ISSUE THREAD

**Issue by miimiispets** [Rovak/wallet-web#40]
1 What did you do?
If possible, provide a recipe for reproducing the error.
On account-voting page

2 What did you expect to see?
Search field to search by candidate account address. This enables voters to quickly find candidate they want to vote for.
When this is included: Also keep in mind error pop up if address can not be found. 

3 What did you see instead?
No search field

**Comment by shanadas** [comment]
I have a PR waiting with this implementation as in the screen below.
![image](https://user-images.githubusercontent.com/3648025/38767949-0be11ce6-4009-11e8-9ebb-51c9b26e5294.png)

**Comment by miimiispets** [comment]
Ah this includes search field as well as displaying delegate url, great!
