### ISSUE TITLE
[Bounty] Wallet - Send (correct address warning)

### ISSUE THREAD

**Issue by miimiispets** [Rovak/wallet-web#42]
What did you do?
If possible, provide a recipe for reproducing the error.
On Wallet - Send page

What did you expect to see?
Warning at address field. Warning to indicate something like: "Only enter valid TRON wallet address. Incorrect addresses can lead to trx loss."

What did you see instead?
No warning

**Comment by shanadas** [comment]
So, I re-read your suggestion and made following implementation.
![image](https://user-images.githubusercontent.com/3648025/38766560-19584a2e-3ff1-11e8-91d4-84be27d9f83c.png)

**Comment by marcusyanghe** [comment]
Hi, @miimiispets ,
I am pleased to inform you that you are rewarded TRX from Tron Foundation for your contribution in our Bug Bounty Program in May 2018. Please provide a valid account address that can receive the TRX reward.
Please send the address to my email yanghe@tron.network so we can deliver the TRX on time.
Thanks,
Marcus Yang
