### ISSUE TITLE
Configure URL when running yarn start

### ISSUE THREAD

**Issue by Rovak** [Rovak/wallet-web#43]
Add option to configure the API url when using `yarn start`, example:

```bash
> yarn start --url=http://localhost:1234
```

**Comment by AhnSinYong** [comment]
thanks!

**Comment by Johnsavadkuhi** [comment]
@Rovak 

I'm confused, could you please explain what you mean?

i use  HOST=host PORT=valid_port   yarn start

**Comment by Rovak** [comment]
@Johnsavadkuhi i want the URL which points to the API url to be configurable. The client is created here https://github.com/tronprotocol/wallet-web/blob/master/src/services/api.js#L3 and the url is pointing to tronscan.org by default

**Comment by Johnsavadkuhi** [comment]
thank you
