### ISSUE TITLE
[Bounty] Add French language

### ISSUE THREAD

**Issue by DevObs1** [Rovak/wallet-web#47]
Hi Team,
Can you add the French language?
![image](https://user-images.githubusercontent.com/31596745/38767998-adfab996-3fec-11e8-833d-c94d2a30de10.png)

If necessary, put the files on crowdin to be translated.

Thanks

**Comment by DevObs1** [comment]
Finally I found the file en.js in wallet-web\src\translations
Here is the file fr.js, corresponding to the french translation of the file en.js

[fr.zip](https://github.com/tronprotocol/wallet-web/files/1913054/fr.zip)

**Comment by AhnSinYong** [comment]
add french language
