### ISSUE TITLE
/tokens/create - Additional info [Bounty]

### ISSUE THREAD

**Issue by miimiispets** [Rovak/wallet-web#51]
On the token create page it would be helpfull to token creators to have additional info on this page. For example under the right "Creating a token" column. At least include short definition of "Quote token amount" & "Base token amount"

![bugs tokencreate 1](https://user-images.githubusercontent.com/38192052/38768280-6f3c6394-3ff1-11e8-856b-199f45915696.PNG)

**Comment by shanadas** [comment]
Can you specify what exactly need to be added below each field?

**Comment by Rovak** [comment]
Fixed https://tronscan.org/#/tokens/create

**Comment by miimiispets** [comment]
Hello guys, in the meanwhile Rovak pushed a large update of this page. We allready discussed it, it's come a nice way compared to the earlier version.
