### ISSUE TITLE
/tokens/create - Token creation cost [Bounty]

### ISSUE THREAD

**Issue by miimiispets** [Rovak/wallet-web#52]
Before creation creator has to acknowledge spending 1024 trx for creating the token.
Based on reactions from other TRON supporters and reading through twitter postst and forum questions, many still do not understand this concept. Confusion largely lies in the fact whether it is a one time cost only, or whether each newly created coin costs 1024trx.

- I think the text next to the tickbox could be improved a little by saying something in the lines of: "I confirm that creating the total supply of the token costs a one time total fee of 1024 TRX."

![suggestion tokencreate 2](https://user-images.githubusercontent.com/38192052/38768312-1599538c-3ff2-11e8-98e2-f34c0d1be6f3.PNG)

**Comment by shanadas** [comment]
How about other languages? Does the statement makes sense in Korean, Portuguese and Arabic? Just to understand, should this be addressed in all languages or not.

**Comment by miimiispets** [comment]
I agree with Shanadas that this statement should make sence in all languages. Unfortunately I do not speak Korean, Portuguese or Arabic :)
