### ISSUE TITLE
[Bounty] Creating a token - limit the size of the year field

### ISSUE THREAD

**Issue by DevObs1** [Rovak/wallet-web#55]
When manually entering a start or end date, the year is not limited to 4 characters.

Expected: when a user enters 4 characters, it is necessary to automatically switch to the time field.

![image](https://user-images.githubusercontent.com/31596745/38772114-a25abde6-402f-11e8-9078-e82c61168c62.png)

**Comment by AhnSinYong** [comment]
I added a limit of 4 characters for the year.
