### ISSUE TITLE
Loading data

### ISSUE THREAD

**Issue by DevObs1** [Rovak/wallet-web#58]
the data do not load on the website https://tronscan.org

![image](https://user-images.githubusercontent.com/31596745/38775548-b0189664-4085-11e8-8b4a-dfa1e9cfee03.png)

![image](https://user-images.githubusercontent.com/31596745/38775550-b853510c-4085-11e8-8809-37c26be9356a.png)

![image](https://user-images.githubusercontent.com/31596745/38775553-bfdf06f0-4085-11e8-91d3-dad85a97b6a0.png)

![image](https://user-images.githubusercontent.com/31596745/38775554-c8ef5dc6-4085-11e8-8ce5-729dd91d700c.png)

**Comment by Rovak** [comment]
duplicates #1, right now there aren't any errors shown when the node from which the data is requested is offline

**Comment by DevObs1** [comment]
Hi @Rovak,

it is still relevant. I can not use the website, the data does not load.
