### ISSUE TITLE
[Bounty] SSL should be mandatory when entering http://git.razko.nl/wallet-web/#/login

### ISSUE THREAD

**Issue by lazarovicedo** [Rovak/wallet-web#60]
For obvious reasons access to the web wallet should always be SSL enforced, included testing environment. Not only for security reasons but for a question of trust on the image of the whole TRON project. 
http://git.razko.nl/wallet-web/#/login

**Comment by Rovak** [comment]
where did you find this link? That was a temporary place where i hosted my prototype. The latest versions can be found on https://tronscan.org and https://trxscan.org

**Comment by lazarovicedo** [comment]
https://github.com/tronprotocol/Documentation/blob/master/Running_a_delegate_EN.md

**Comment by lazarovicedo** [comment]
and on the chinese version of the same doc: 
https://github.com/tronprotocol/Documentation/blob/master/Running_a_delegate_CN.md

**Comment by Rovak** [comment]
thanks, i'll change the link

**Comment by Rovak** [comment]
https://github.com/tronprotocol/Documentation/pull/15
