### ISSUE TITLE
[Bounty] Spanish translation (contribution)

### ISSUE THREAD

**Issue by lazarovicedo** [Rovak/wallet-web#61]
In case no one is doing it already, I would like to contribute translating to spanish the tron web wallet. I'm spanish native speaker.
Should I post the lang file here?

**Comment by Rovak** [comment]
You can use the https://github.com/tronprotocol/wallet-web/blob/master/src/translations/en.js file and translate the English strings to spanish. You can then paste the translated file here or make a pull request.

**Comment by lazarovicedo** [comment]
[es.js.zip](https://github.com/tronprotocol/wallet-web/files/1913343/es.js.zip)

**Comment by AhnSinYong** [comment]
spanish was added by Johnsavadkuhi.
