### ISSUE TITLE
Make URLS clickable

### ISSUE THREAD

**Issue by Rovak** [Rovak/wallet-web#80]
In the token overview and the representatives overview there are URL's shown which aren't clickable. 

Make them clickable. When clicked show a warning that the user should follow the link on his own risk.

**Comment by Jacob8765** [comment]
I can work on this later today.

**Comment by Rovak** [comment]
Great, make a reusable component for it, something like this:

```html
<ExternalLink url={url}>Text</ExternalLink>
```

**Comment by Jacob8765** [comment]
#85
