### ISSUE TITLE
Cannot get testing TRX

### ISSUE THREAD

**Issue by funoverip** [Rovak/wallet-web#86]
Hi,

I've just created an account (A06F490F956BFDF81DA69C43ED403C0107600C1444) but couldn't get testing TRX.

Right after the creation, I get an unknown error:

![screenshot 2018-04-17_08-15-03](https://user-images.githubusercontent.com/7892650/38851989-4c66289a-4218-11e8-83d1-3f337c10852f.png)

Then If I click manually on **Request TRX for testing**, it says that I've already requested them.

![screenshot 2018-04-17_08-18-26](https://user-images.githubusercontent.com/7892650/38852038-7d813352-4218-11e8-91f8-21c1eaae9f79.png)

Environment: Chrome Version 65.0.3325.181 (Official Build) (64-bit) on OSX

**Comment by fbsobreira** [comment]
Your address starts with A0, you should 've using an old version of the node wallet api, try clone the repository again, or update the package manually

**Comment by funoverip** [comment]
Hi,
Thanks for the feedback. It happened on the online https://tronscan.org website. But now it seems to works correctly.

Edit: I wonder if I don't suffer from caching issues something on this website.

Cheers.

**Comment by Rovak** [comment]
@funoverip there are indeed some caching issues sometimes when deploying a new version, i'll be fixing this oon
