### ISSUE TITLE
[bounty] sending TRON with decimals

### ISSUE THREAD

**Issue by lazarovicedo** [Rovak/wallet-web#91]
When sending TRON with 3 decimals, the quantity typed is formatted incorrectly.
ie.:  0.045 is incorrectly formatted to 0.45

**Comment by fbsobreira** [comment]
Hi @Rovak , I think you can close this issue? Or is there anything else that needs to be considered here?

**Comment by tronmarcus** [comment]
Hi, @lazarovicedo  lazarovicedo,
I am pleased to inform you that you are rewarded TRX from Tron Foundation for your contribution in our Bug Bounty Program in May 2018. Please provide a valid account address that can receive the TRX reward.
Please send the address to my email yanghe@tron.network so we can deliver the TRX on time.
Thanks,
Marcus Yang
