### ISSUE TITLE
[bounty] account with negative number of TRX

### ISSUE THREAD

**Issue by lazarovicedo** [Rovak/wallet-web#92]
I don't know know if this related to wallet or api, but it looks like an important bug:
On https://trxscan.org/#/accounts there is an account with -9.223.372.036.854,78 TRX
account: 27WtBq2KoSy5v8VnVZBZHHJcDuWNiSgjbE3
How would it be possible to be a negative number?

**Comment by Rovak** [comment]
This is done in the conf file https://github.com/tronprotocol/java-tron/blob/develop/src/main/resources/config.conf#L99
