### ISSUE TITLE
[Bounty] After Voting, same number of TRX are available

### ISSUE THREAD

**Issue by lazarovicedo** [Rovak/wallet-web#95]
At the voting section https://tronscan.org/#/account/votes
New account, 10000TRX remaining for voting. After voting and reloading the page the same number of TRX remain. I think it should count total voting assigned to candidates and subtract that quantity from TRX remaining showing the user the right quantity available for voting.

**Comment by bondibox** [comment]
I believe that's a feature, not a bug. TRX holders can vote as many times as they like, only the last round of votes will count. You can change your votes before midnight.  If you only vote 4000 out of 10,000 you don't get to go back and add the extra 6000. You revote all 10,000 until you get it right.

**Comment by dbuarque** [comment]
I think that to improve the user experience the vote should be subtracted and renewed with a countdown timer.

**Comment by Rovak** [comment]
It is intended to show the same votes after you voted. Only the most recent votes from a user will be used by the next vote cycle. And the user should be able to distribute their votes differently if they feel like it.

This could be clarified in the help text to the right
